#!/bin/sh

SUCCESS=0
BATS_RESULT_IS_FAILURE=10

tests=$(git diff --staged --name-only --diff-filter ACMR | grep -E '\.bats$')
[ -z "$tests" ] && exit $SUCCESS

git stash -q --keep-index

# shellcheck disable=SC2086
test/bats/bin/bats $tests
status=$?

git stash pop -q

if [ "$status" -gt 0 ]; then
    exec 1>&2
    # shellcheck disable=SC2086
    cat <<EOT
abort: the result of the bats tests, which are staging, have failed

<tests>:
$(git diff --staged --name-status -- $tests)

EOT
    exit $BATS_RESULT_IS_FAILURE
fi
